# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Execute server & install minimum dependencies
      run: python -m main --install-pkgs --skip-tf-install --skip-torch-install

    - name: Run tests
      run: python -m unittest discover tests

  build-release:
    needs: build-and-test
    if: ${{ success() }}
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Shorten SHA
      id: shorten_sha
      run: echo "::set-output name=sha::$(echo ${GITHUB_SHA:0:7})"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.shorten_sha.outputs.sha }}
        release_name: master-${{ steps.shorten_sha.outputs.sha }}
        draft: false
        prerelease: false