name: Continuous Integration

on:
  push:
    branches:
      - master
    paths:
      - 'llama_api/**'
  pull_request:
    branches:
      - master
    paths:
      - 'llama_api/**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Python, install dependencies, and run tests
      run: |
        python -m pip install --upgrade pip
        python -m llama_api.server.app_settings --install-pkgs
        python -m unittest discover tests
